on:
  workflow_dispatch:  # 允许手动触发工作流

name: Build and Upload APK

env:
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  build:
    name: Build and Upload APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # 设置 Java 环境以便构建 Android 应用
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '1.8'

      # Gradle 缓存加速构建
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 设置 Flutter 环境
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # 配置签名属性
      - name: Configure signing properties
        run: |
            echo "keyAlias=${{ secrets.KEY_ALIAS }}" > ${{env.PROPERTIES_PATH}}
            echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> ${{env.PROPERTIES_PATH}}
            echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> ${{env.PROPERTIES_PATH}}

      # 解码 keystore 文件
      - name: Decode keystore file
        run: echo "${{ secrets.KEY_STORE }}" | base64 --decode > android/app/key.jks

      # 获取 Flutter 依赖
      - run: flutter pub get

      # 构建 APK
      - name: Build APK
        run: flutter build apk --release --flavor github

      # 上传 APK 文件
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: afA-APK
          path: build/app/outputs/flutter-apk/app-github-release.apk
